name: Publish to NuGet

on:
  push:
    tags:
      - "v*" # Triggers on tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write # Required to create releases
  packages: write # Required for package operations

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for MinVer to work properly

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      # Skip tests since none exist yet

      - name: Pack NuGet packages
        run: dotnet pack --configuration Release --no-build --output ./packages

      - name: Publish to NuGet
        run: dotnet nuget push "./packages/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
