name: Publish to NuGet

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore



      - name: Pack NuGet packages (Abstraction)
        run: dotnet pack DataAccess.SQL.Abstraction/DataAccess.SQL.Abstraction.csproj --configuration Release --no-build --output ./packages

      - name: Pack NuGet packages (PostgreSql)
        run: dotnet pack DataAccess.SQL.PostgreSql/DataAccess.SQL.PostgreSql.csproj --configuration Release --no-build --output ./packages

      - name: Publish to NuGet
        run: dotnet nuget push "./packages/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate